import fs from 'node:fs/promises'
import path from 'node:path'
import { test, expect } from '../fixtures.mjs'
import { installModelComparisonFixture, comparisonFixture, SELECTED_TIME } from '../model-comparison-fixture.mjs'

const captureRoot=process.env.PROJECTAMO_COMPARISON_CAPTURE_DIR
async function capture(page,testInfo,label) {
  if(!captureRoot) return
  await fs.mkdir(captureRoot,{recursive:true})
  const scroller=page.locator('.mc-page')
  if(await scroller.count()) await scroller.evaluate(el=>{el.scrollTop=0})
  await page.screenshot({path:path.join(captureRoot,`${testInfo.project.name}-${label}.png`)})
  for(const section of await page.locator('[data-section]').all()) {
    const id=await section.getAttribute('data-section')
    for (const [index,chart] of (await section.locator('.mc-chart-wrap').all()).entries()) {
      await chart.scrollIntoViewIfNeeded()
      await expect(chart).toBeInViewport()
      await page.screenshot({path:path.join(captureRoot,`${testInfo.project.name}-${label}-${id}-chart-${index}.png`)})
    }
  }
  if(await scroller.count()) await scroller.evaluate(el=>{el.scrollTop=0})
}
async function noOverflow(page) {
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
}
const temperatureTable=page=>page.getByRole('table',{name:'기온과 상대습도 시간별 비교',exact:true})

test.describe('airport-model-comparison',()=>{
  test('clicking charts never changes the selection, time columns or chart size',async({page},testInfo)=>{
    await installModelComparisonFixture(page)
    const initial='2026-09-06T04:00:00.000Z'
    await page.goto(`/airport/RKPU/models?valid_at=${encodeURIComponent(initial)}`)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    for(const [tab,units] of [['바람',['kt']],['강수',['mm']],['운고·운량',['ft']],['기온·RH',['°C','%']]]) {
      await page.getByRole('tab',{name:tab,exact:true}).click()
      const columns=await page.getByRole('columnheader').allTextContents()
      for(const unit of units) {
        const chart=page.getByRole('img',{name:`모델별 ${unit} 추세 그래프`,exact:true})
        await chart.scrollIntoViewIfNeeded()
        const before=await chart.boundingBox(),viewBox=await chart.getAttribute('viewBox')
        const point=chart.getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/)
        await point.scrollIntoViewIfNeeded()
        const p=await point.boundingBox(),c=await chart.boundingBox(),position={x:p.x+p.width/2-c.x,y:p.y+p.height/2-c.y}
        if(testInfo.project.use.hasTouch) await chart.tap({position});else await chart.click({position})
        await expect(page).toHaveURL(new RegExp(encodeURIComponent(initial)))
        await expect(chart).toHaveAttribute('viewBox',viewBox)
        expect(await page.getByRole('columnheader').allTextContents()).toEqual(columns)
        const after=await chart.boundingBox()
        expect(after.width).toBeCloseTo(before.width,1);expect(after.height).toBeCloseTo(before.height,1)
        await page.mouse.move(0,0)
        await expect(page.getByRole('tooltip')).toHaveCount(0)
      }
    }
  })

  test('chart values appear in a floating tooltip on hover and keyboard focus',async({page},testInfo)=>{
    await installModelComparisonFixture(page)
    await page.goto(`/airport/RKPU/models?valid_at=${encodeURIComponent(SELECTED_TIME)}`)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    const chart=page.getByRole('img',{name:'모델별 kt 추세 그래프',exact:true})
    await chart.scrollIntoViewIfNeeded()
    await expect(page.getByRole('tooltip')).toHaveCount(0)
    await expect(page.getByText('그래프 점을 선택하면 실행시각·F-hour 상세를 고정합니다.',{exact:true})).toHaveCount(0)
    const point=chart.getByLabel(/^KIM 돌풍 2026-09-06T09:00:00.000Z,/)
    if(testInfo.project.use.hasTouch) await point.focus();else await point.hover()
    const tooltip=page.getByRole('tooltip')
    await expect(tooltip).toBeVisible()
    for(const model of ['KIM','ECMWF','GFS','ICON']) await expect(tooltip.getByText(model,{exact:true})).toBeVisible()
    await expect(tooltip).toContainText('09.06 18:00 KST')
    if(!testInfo.project.use.hasTouch) {
      await tooltip.hover()
      await expect(tooltip).toBeVisible()
      await page.mouse.move(0,0)
      await expect(tooltip).toHaveCount(0)
      const pointBox=await point.boundingBox(),chartBox=await chart.boundingBox()
      await page.mouse.move(pointBox.x+pointBox.width/2,chartBox.y+12)
      await expect(tooltip).toContainText('09.06 18:00 KST')
      await expect(page).toHaveURL(new RegExp(encodeURIComponent(SELECTED_TIME)))
    }
    const bounds=await tooltip.boundingBox(),viewport=page.viewportSize()
    expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.y).toBeGreaterThanOrEqual(0)
    expect(bounds.x+bounds.width).toBeLessThanOrEqual(viewport.width)
    expect(bounds.y+bounds.height).toBeLessThanOrEqual(viewport.height)
    if(captureRoot) { await fs.mkdir(captureRoot,{recursive:true});await page.screenshot({path:path.join(captureRoot,`${testInfo.project.name}-wind-tooltip.png`)}) }
    await page.keyboard.press('Escape')
    await expect(tooltip).toHaveCount(0)
    await page.getByRole('tab',{name:'바람',exact:true}).focus()
    await point.focus()
    await expect(tooltip).toBeVisible()
    await point.press('Enter')
    await expect(page).toHaveURL(new RegExp(encodeURIComponent(SELECTED_TIME)))
    await page.getByRole('button',{name:'전체 보기',exact:true}).click()
    await expect(tooltip).toHaveCount(0)
  })

  test('value cells toggle cloud and temperature extras without separate information labels',async({page},testInfo)=>{
    await installModelComparisonFixture(page)
    await page.goto(`/airport/RKPU/models?valid_at=${encodeURIComponent(SELECTED_TIME)}`)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await page.getByRole('tab',{name:'기온·RH',exact:true}).click()
    const temperatureCell=temperatureTable(page).getByTitle(/^ECMWF · 2026-09-06T09:00:00.000Z/)
    const pair=temperatureCell.getByText('23.0°C / 74%',{exact:true})
    await expect(temperatureCell.getByText('보조 정보',{exact:true})).toHaveCount(0)
    await expect(temperatureCell.getByText(/이슬점/)).toBeHidden()
    if(testInfo.project.use.hasTouch) await pair.tap();else await pair.click()
    await expect(temperatureCell.getByText(/이슬점.*기압/)).toBeVisible()
    await pair.click()
    await expect(temperatureCell.getByText(/이슬점/)).toBeHidden()
    await page.getByRole('tab',{name:'운고·운량',exact:true}).click()
    const cell=page.getByRole('table',{name:'운고와 운량 시간별 비교',exact:true}).getByTitle(/^ECMWF · 2026-09-06T09:00:00.000Z/)
    const value=cell.getByText('4,524 ft',{exact:true})
    await expect(cell.getByText(/전\/저\/중\/상/)).toBeHidden()
    if(testInfo.project.use.hasTouch) await value.tap();else await value.click()
    await expect(cell.getByText(/전\/저\/중\/상/)).toBeVisible()
    expect((await cell.boundingBox()).height).toBeLessThan(250)
    await capture(page,testInfo,'RKPU-ceiling-expanded')
    const control=cell.getByLabel('4,524 ft',{exact:true})
    await control.focus();await control.press('Enter')
    await expect(cell.getByText(/전\/저\/중\/상/)).toBeHidden()
    await noOverflow(page)
  })

  test('loading and supported airport without AMOS retain navigation and explicit missing rainfall',async({page},testInfo)=>{
    await installModelComparisonFixture(page)
    let release
    const pending=new Promise(resolve=>{release=resolve})
    const payload=comparisonFixture({airport_icao:'RKPK'})
    payload.airport.name='김해국제공항'
    payload.observations.amos=[]
    await page.route('**/api/airport/RKPK/model-comparison',async route=>{
      await pending
      await route.fulfill({json:payload})
    })
    await page.goto('/airport/RKPK/models',{waitUntil:'domcontentloaded'})
    await expect(page.getByRole('status')).toContainText('불러오는 중')
    await expect(page.getByRole('link',{name:'공항 패널로 돌아가기',exact:true})).toBeVisible()
    await page.getByRole('group',{name:'표시 시간대'}).getByRole('button',{name:'UTC',exact:true}).click()
    await capture(page,testInfo,'RKPK-loading')
    release()
    await expect(page.getByRole('heading',{name:/김해국제공항 상세 예보 분석/})).toBeVisible()
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await page.getByRole('tab',{name:'강수',exact:true}).click()
    const amos=page.getByRole('table',{name:'시간당 강수량 비교',exact:true}).getByRole('row').filter({has:page.getByRole('rowheader',{name:'AMOS 실측',exact:true})})
    await expect(amos).toContainText('자료 없음')
    await expect(amos).not.toContainText('0.0 mm')
    await capture(page,testInfo,'RKPK-without-amos')
    await noOverflow(page)
  })

  test('temperature and RH use vertically separated charts on the same time axis',async({page})=>{
    await installModelComparisonFixture(page)
    await page.goto('/airport/RKPU/models')
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await page.getByRole('tab',{name:'기온·RH',exact:true}).click()
    const temperature=page.getByRole('region',{name:'기온 그래프',exact:true})
    const humidity=page.getByRole('region',{name:'상대습도 그래프',exact:true})
    await expect(temperature).toBeVisible()
    await expect(humidity).toBeVisible()
    const first=await temperature.boundingBox(),second=await humidity.boundingBox()
    expect(second.y).toBeGreaterThanOrEqual(first.y+first.height)
    await expect(temperature.getByRole('img',{name:'모델별 °C 추세 그래프',exact:true})).toBeVisible()
    await expect(humidity.getByRole('img',{name:'모델별 % 추세 그래프',exact:true})).toBeVisible()
    await expect(temperature.getByRole('img',{name:'모델별 °C 추세 그래프',exact:true}).locator('path[stroke-dasharray]')).toHaveCount(0)
    const column=await temperatureTable(page).getByRole('button',{name:'09.06 18:00 KST',exact:true}).boundingBox()
    const sample=await temperature.getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/).boundingBox()
    expect(Math.abs(column.x+column.width/2-sample.x-sample.width/2)).toBeLessThan(3)
    await humidity.getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/).scrollIntoViewIfNeeded()
    await humidity.getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/).focus()
    await expect(page.getByRole('tooltip')).toContainText('23.0°C / 74%')
    await expect(page.getByRole('tooltip')).toHaveCount(1)
  })
  test('panel entry, paired values, UTC instant, refresh and return',async({page,consoleMessages},testInfo)=>{
    await installModelComparisonFixture(page)
    await page.goto('/?airport=RKPU',{waitUntil:'domcontentloaded'})
    const panel=page.locator('.airport-panel')
    await expect(panel.getByRole('heading',{name:'상세 예보 분석',exact:true})).toBeVisible()
    await expect(panel.getByRole('region',{name:'상세 예보 분석 요약'})).toContainText('09.06 18:00 KST')
    const link=panel.getByRole('link',{name:'분석 화면 열기 ↗',exact:true})
    await expect(link).toHaveAttribute('href',new RegExp(encodeURIComponent(SELECTED_TIME)))
    await link.click()
    await expect(page.getByRole('heading',{name:/울산공항 상세 예보 분석/})).toBeVisible()
    await expect(page).toHaveURL(new RegExp(encodeURIComponent(SELECTED_TIME)))
    await noOverflow(page);await capture(page,testInfo,'all')
    expect(await page.locator('.mc-page').evaluate(el=>el.clientHeight<=window.innerHeight && el.scrollHeight>el.clientHeight)).toBe(true)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await capture(page,testInfo,'wind')
    await page.getByRole('tab',{name:'기온·RH',exact:true}).click()
    const table=temperatureTable(page),ec=table.getByRole('row').filter({has:page.getByRole('rowheader',{name:'ECMWF',exact:true})})
    await expect(ec.locator('td.is-selected')).toContainText('23.0°C / 74%')
    const humidityPoint=page.getByRole('region',{name:'상대습도 그래프',exact:true}).getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/)
    await expect(humidityPoint).toHaveAttribute('aria-label',/74 %/)
    const selectedPoint=page.getByRole('region',{name:'기온 그래프',exact:true}).getByLabel(/^ECMWF 2026-09-06T09:00:00.000Z,/)
    await selectedPoint.scrollIntoViewIfNeeded()
    await selectedPoint.focus()
    await expect(page.getByRole('tooltip')).toContainText('23.0°C / 74%')
    await page.getByRole('button',{name:'전체 보기',exact:true}).click()
    await expect(page.getByRole('tooltip')).toHaveCount(0)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await expect(table.getByRole('button',{name:'09.06 18:00 KST',exact:true})).toHaveAttribute('aria-pressed','true')
    await expect(table.getByRole('rowheader',{name:'TAF',exact:true})).toHaveCount(0)
    await page.getByRole('group',{name:'표시 시간대'}).getByRole('button',{name:'UTC',exact:true}).click()
    await expect(table.getByRole('button',{name:'09.06 09:00 UTC',exact:true})).toHaveAttribute('aria-pressed','true')
    await page.reload()
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await page.getByRole('tab',{name:'기온·RH',exact:true}).click()
    await expect(temperatureTable(page).getByRole('row').filter({has:page.getByRole('rowheader',{name:'ECMWF',exact:true})}).locator('td.is-selected')).toContainText('23.0°C / 74%')
    await capture(page,testInfo,'temp-rh');await noOverflow(page)
    await page.getByRole('link',{name:'공항 패널로 돌아가기',exact:true}).click()
    await expect(page.locator('.airport-panel').getByRole('link',{name:'분석 화면 열기 ↗',exact:true})).toBeVisible()
    expect(consoleMessages.filter(m=>m.type==='pageerror')).toEqual([])
  })

  test('EC actual F018, paired null, model methods and conditional observations',async({page,consoleMessages},testInfo)=>{
    await installModelComparisonFixture(page)
    await page.goto(`/airport/RKPU/models?valid_at=${encodeURIComponent(SELECTED_TIME)}`)
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await page.getByRole('tab',{name:'기온·RH',exact:true}).click()
    const table=temperatureTable(page)
    const ec=table.getByRole('row').filter({has:page.getByRole('rowheader',{name:'ECMWF',exact:true})})
    await expect(ec.locator('td[title*="F018"]')).toContainText('23.0°C / 74%')
    const icon=table.getByRole('row').filter({has:page.getByRole('rowheader',{name:'ICON',exact:true})})
    await expect(icon.locator('td[title*="F004"]')).toContainText('자료 없음 / 67%')
    const point=page.getByRole('region',{name:'기온 그래프',exact:true}).getByLabel(/ECMWF 2026-09-06T18:00:00.000Z,/)
    await table.getByRole('button',{name:'09.07 03:00 KST',exact:true}).click()
    await point.scrollIntoViewIfNeeded();await point.focus()
    await expect(page).toHaveURL(/18%3A00%3A00/)
    await expect(ec.locator('td.is-selected')).toHaveAttribute('title',/F018/)
    await page.getByRole('tab',{name:'운고·운량',exact:true}).click()
    const ceiling=page.getByRole('table',{name:'운고와 운량 시간별 비교',exact:true})
    for(const [model,method] of [['KIM','운량·응결물 기반 추정'],['ECMWF','습도 기반 추정'],['GFS','모델 자체 운고'],['ICON','압력면 기반 추정']]) {
      const row=ceiling.getByRole('row').filter({has:page.getByRole('rowheader',{name:model,exact:true})})
      await expect(row.getByRole('rowheader',{name:model,exact:true})).toContainText(method)
      await expect(row.getByText(method,{exact:true})).toHaveCount(1)
      await expect(row.locator('td.is-selected')).not.toContainText(method)
      expect((await row.boundingBox()).height).toBeLessThan(250)
    }
    await expect(ceiling.getByRole('row').filter({has:page.getByRole('rowheader',{name:'GFS',exact:true})}).locator('td[title*="F004"]')).toContainText('운고 없음')
    await expect(ceiling.getByRole('row').filter({has:page.getByRole('rowheader',{name:'ICON',exact:true})}).locator('td[title*="F006"]')).toContainText('입력자료 없음')
    const ceilingPoint=page.getByLabel(/^ECMWF 2026-09-06T18:00:00.000Z,/)
    await ceilingPoint.scrollIntoViewIfNeeded();await ceilingPoint.focus()
    const detail=page.getByRole('tooltip')
    for(const model of ['KIM','ECMWF','GFS','ICON']) await expect(detail.getByText(model,{exact:true})).toBeVisible()
    await expect(detail).toContainText('보간 1시간 자료')
    await expect(page.getByText(/상세 근거|산출 근거/)).toHaveCount(0)
    await expect(detail).toContainText('F018')
    const detailBox=await detail.boundingBox()
    expect(detailBox.x).toBeGreaterThanOrEqual(0)
    expect(detailBox.width).toBeLessThanOrEqual(page.viewportSize().width)
    await capture(page,testInfo,'ceiling-comparison')
    await capture(page,testInfo,'ceiling')
    await page.getByRole('tab',{name:'강수',exact:true}).click()
    const rain=page.getByRole('table',{name:'시간당 강수량 비교',exact:true})
    expect(await rain.getByRole('rowheader').allTextContents()).toEqual(['METAR 현재날씨','TAF','AMOS 실측','KIM','ECMWF','GFS','ICON'])
    await expect(rain.getByRole('row').filter({has:page.getByRole('rowheader',{name:'TAF',exact:true})})).toContainText('TEMPO')
    await capture(page,testInfo,'precipitation');await noOverflow(page)
    await expect(page.getByText(/순위|1등|자동 변화 감지/)).toHaveCount(0)
    await expect(page.getByRole('complementary',{name:'준비 중인 참고 자료'})).toContainText('현재 공항·실행자료와 연결되지 않음')
    expect(consoleMessages.filter(m=>m.type==='pageerror')).toEqual([])
  })

  for(const scenario of ['partial','empty']) test(`${scenario} data retains explicit model rows and missing states`,async({page},testInfo)=>{
    await installModelComparisonFixture(page,{scenario})
    await page.goto('/airport/RKPU/models')
    await expect(page.getByRole('region',{name:'분석 기준'})).toContainText(scenario==='partial'?'일부 모델 준비':'모델 자료 없음')
    await page.getByRole('button',{name:'요소별 보기',exact:true}).click()
    await expect(page.getByRole('table',{name:'지상 바람 시간별 비교',exact:true}).getByRole('rowheader',{name:'GFS',exact:true})).toBeVisible()
    await capture(page,testInfo,scenario);await noOverflow(page)
  })

  test('refresh failure retains last values and recovery clears error',async({page})=>{
    const fixture=await installModelComparisonFixture(page)
    await page.clock.install({time:new Date('2026-09-06T08:20:00Z')})
    await page.goto('/airport/RKPU/models')
    await expect(page.getByRole('region',{name:'분석 기준'})).toContainText('4개 모델 준비')
    fixture.setScenario('error');await page.clock.fastForward(61_000)
    await expect(page.getByRole('status')).toContainText('마지막 성공 자료를 계속 표시합니다')
    await expect(page.getByRole('table',{name:'기온과 상대습도 시간별 비교'}).getByRole('row').filter({has:page.getByRole('rowheader',{name:'ECMWF',exact:true})}).locator('td.is-selected')).toContainText('23.0°C / 74%')
    fixture.setScenario('ready');fixture.setNow('2026-09-06T09:21:00.000Z');await page.clock.fastForward(61_000)
    await expect(page.getByText('갱신에 실패했습니다.',{exact:false})).toHaveCount(0)
    await expect(page).toHaveURL(new RegExp(encodeURIComponent(SELECTED_TIME)))
    expect(fixture.requests).toBeGreaterThanOrEqual(3)
  })

  test('unsupported airports never request comparison upstream',async({page})=>{
    const fixture=await installModelComparisonFixture(page)
    await page.goto('/airport/RJAA/models')
    await expect(page.getByRole('heading',{name:'지원하지 않는 공항입니다.'})).toBeVisible()
    expect(fixture.requests).toBe(0)
  })
})
