import { test, expect } from '../fixtures.mjs'
import { CURRENT_VERSION } from '../../src/features/about/changelog.js'

async function startMap(page, name) {
  await page.addInitScript((version) => { localStorage.setItem('amo.tour.v1.done', 'true'); localStorage.setItem('projectamo:lastSeenVersion', version) }, CURRENT_VERSION)
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: '내 지도', exact: true }).click()
  await page.getByRole('button', { name: '새 지도', exact: true }).click()
  await page.getByRole('textbox', { name: '지도 이름', exact: true }).fill(name)
  await page.getByRole('button', { name: '만들기', exact: true }).click()
  await page.waitForFunction(() => window.__map?.getLayer('my-map-edit-line'))
  await page.evaluate(() => window.__map.jumpTo({ center: [127, 37], zoom: 8 }))
}
const features = (page, source = 'my-map-src') => page.evaluate((id) => window.__map?.getSource(id)?.serialize().data.features ?? [], source)
const preview = async (page) => (await features(page, 'my-map-edit-preview')).find((feature) => feature.properties.role === 'shape')?.geometry
const click = (page, x, y) => page.locator('.mapboxgl-canvas').click({ position: { x, y } })
async function drag(page, from, to) {
  const box = await page.locator('.mapboxgl-canvas').boundingBox()
  await page.mouse.move(box.x + from.x, box.y + from.y); await page.mouse.down()
  await page.mouse.move(box.x + to.x, box.y + to.y, { steps: 8 }); await page.mouse.up()
}
async function handle(page, role, index = 0) {
  await expect.poll(() => page.evaluate(({ role, index }) => window.__map.queryRenderedFeatures({ layers: ['my-map-edit-vertex', 'my-map-edit-midpoint'] }).some((f) => f.properties.role === role && Number(f.properties.index ?? 0) === index), { role, index })).toBe(true)
  return page.evaluate(({ role, index }) => {
    const feature = window.__map.getSource('my-map-edit-preview').serialize().data.features.find((f) => f.properties.role === role && Number(f.properties.index ?? 0) === index)
    return window.__map.project(feature.geometry.coordinates)
  }, { role, index })
}
async function saved(page, name) {
  return page.evaluate(async (name) => {
    const db = await new Promise((resolve) => { const r = indexedDB.open('projectamo-my-map-account-v1'); r.onsuccess = () => resolve(r.result) })
    const rows = await new Promise((resolve) => { const r = db.transaction('completed').objectStore('completed').getAll(); r.onsuccess = () => resolve(r.result) })
    db.close(); return rows.map((row) => row.document.document ?? row.document).find((document) => document.name === name) ?? null
  }, name)
}

test('my-map 작성 전범위: 면 닫기·전체 이동·꼭짓점·원 반경·undo redo', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 기하 편집 계약')
  test.setTimeout(120000)
  await startMap(page, '기하 검증')
  await page.getByRole('button', { name: '면', exact: true }).click()
  await click(page, 780, 290); await click(page, 950, 290); await click(page, 950, 450)
  await page.keyboard.press('Enter')
  await expect.poll(async () => (await features(page)).length).toBe(1)
  const original = (await features(page))[0].geometry
  expect(original.coordinates[0]).toHaveLength(4)
  expect(original.coordinates[0][0]).toEqual(original.coordinates[0].at(-1))
  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  await handle(page, 'vertex')
  await drag(page, { x: 895, y: 335 }, { x: 935, y: 360 })
  await expect.poll(() => preview(page)).not.toEqual(original)
  // 형태 미리보기는 완료본 소스를 덮어쓰지 않는다.
  expect((await features(page))[0].geometry).toEqual(original)
  await page.getByRole('button', { name: '완료', exact: true }).click()
  const translated = (await features(page))[0].geometry
  const delta = translated.coordinates[0][0].map((value, axis) => value - original.coordinates[0][0][axis])
  for (let i = 1; i < 4; i += 1) for (let axis = 0; axis < 2; axis += 1) expect(translated.coordinates[0][i][axis] - original.coordinates[0][i][axis]).toBeCloseTo(delta[axis], 8)
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.poll(async () => (await features(page))[0].geometry).toEqual(original)
  await page.getByRole('button', { name: '다시하기', exact: true }).click()
  await expect.poll(async () => (await features(page))[0].geometry).toEqual(translated)
  await page.getByRole('button', { name: '면 1', exact: true }).click()
  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  const midpoint = await handle(page, 'midpoint', 1)
  await drag(page, midpoint, { x: midpoint.x, y: midpoint.y - 30 })
  await expect.poll(async () => (await preview(page)).coordinates[0].length).toBe(5)
  await page.getByRole('button', { name: '선택 꼭짓점 삭제', exact: true }).click()
  await expect.poll(async () => (await preview(page)).coordinates[0].length).toBe(4)
  const vertex = await handle(page, 'vertex', 0)
  await click(page, vertex.x, vertex.y)
  await page.getByRole('button', { name: '선택 꼭짓점 삭제', exact: true }).click()
  await expect(page.locator('.my-map-error')).toContainText('세 지점')
  expect((await preview(page)).coordinates[0]).toHaveLength(4)
  await page.getByRole('button', { name: '취소', exact: true }).click()
  expect((await features(page))[0].geometry).toEqual(translated)
  await page.getByRole('button', { name: '원', exact: true }).click()
  await click(page, 780, 560); await click(page, 860, 560)
  await expect.poll(async () => (await features(page)).length).toBe(2)
  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  await page.getByRole('spinbutton', { name: '반경 · NM', exact: true }).fill('3.5')
  await page.getByRole('button', { name: '완료', exact: true }).click()
  await expect.poll(async () => (await saved(page, '기하 검증'))?.items.find((item) => item.kind === 'circle')?.definition.radiusNm).toBe(3.5)
  const circle = (await saved(page, '기하 검증')).items.find((item) => item.kind === 'circle')
  expect(circle.geometry.coordinates[0].length).toBeGreaterThan(30)
  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  const center = await handle(page, 'center')
  await drag(page, center, { x: center.x + 35, y: center.y - 20 })
  await page.getByRole('button', { name: '완료', exact: true }).click()
  await expect.poll(async () => (await saved(page, '기하 검증')).items.find((item) => item.kind === 'circle').definition.center).not.toEqual(circle.definition.center)
  expect((await saved(page, '기하 검증')).items.find((item) => item.kind === 'circle').definition.radiusNm).toBe(3.5)
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('geometry-completed.png') })
})

test('my-map 작성 전범위: 좌표 오류·다중 이동·항목 삽입 드래그·그룹 정렬', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 그룹 편집 계약')
  test.setTimeout(120000)
  await startMap(page, '그룹 작업 검증')
  for (const name of ['A', 'B']) {
    await page.getByRole('textbox', { name: '새 그룹 이름', exact: true }).fill(name)
    await page.getByRole('button', { name: '그룹 추가', exact: true }).click()
  }
  const group = (name) => page.locator('.my-map-editor-group').filter({ has: page.getByRole('button', { name: new RegExp(`^${name} \\d+$`) }) })
  await page.getByRole('button', { name: '좌표 여러 줄 입력', exact: true }).click()
  const bulk = page.getByRole('region', { name: '좌표 여러 줄 입력', exact: true })
  await bulk.getByRole('combobox', { name: '대상 그룹' }).selectOption({ label: 'A' })
  await bulk.locator('textarea').fill('첫째\t37\t127\n잘못된 점\t100\t127')
  await expect(bulk.locator('.is-error')).toContainText('2행')
  await expect(bulk.getByRole('button', { name: '점 1개 추가', exact: true })).toBeDisabled()
  await bulk.locator('textarea').fill('첫째\t37\t127\n둘째\t37.1\t127.1\n셋째\t37.2\t127.2')
  await bulk.getByRole('button', { name: '점 3개 추가', exact: true }).click()
  if (await group('A').locator('.my-map-tree-caret').getAttribute('aria-expanded') !== 'true') await group('A').locator('.my-map-tree-caret').click()
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●둘째', '●셋째'])
  await page.getByRole('button', { name: '선택', exact: true }).click()
  await page.getByRole('checkbox', { name: '첫째 선택', exact: true }).check()
  await page.getByRole('checkbox', { name: '셋째 선택', exact: true }).check()
  await page.getByRole('combobox', { name: '선택 항목 이동할 그룹', exact: true }).selectOption({ label: 'B' })
  if (await group('B').locator('.my-map-tree-caret').getAttribute('aria-expanded') !== 'true') await group('B').locator('.my-map-tree-caret').click()
  await expect(group('B').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째'])
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●둘째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●둘째', '●셋째'])
  // 그룹도 실제 드래그로 정렬하고 가상 영역과 함께 순서를 검증한다.
  await group('B').locator('.my-map-editor-group-head > .my-map-editor-grip').dragTo(group('A').locator('.my-map-editor-group-name'))
  await expect(page.locator('.my-map-editor-group-name')).toHaveText(['그룹 없는 항목 0', 'B 0', 'A 3'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(page.locator('.my-map-editor-group-name')).toHaveText(['그룹 없는 항목 0', 'A 3', 'B 0'])
  await page.getByRole('button', { name: '선택 마침', exact: true }).click()
  const items = group('A').locator('.my-map-editor-item')
  await items.nth(2).dragTo(items.nth(0))
  await expect.soft(group('A').locator('.my-map-editor-item-name'), '항목 앞 드롭은 해당 위치에 한 번만 삽입되어야 한다').toHaveText(['●셋째', '●첫째', '●둘째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.soft(group('A').locator('.my-map-editor-item-name'), '드롭 한 번은 되돌리기 한 번으로 원래 순서가 되어야 한다').toHaveText(['●첫째', '●둘째', '●셋째'])
  await page.getByRole('searchbox', { name: '항목 이름 검색', exact: true }).fill('첫째')
  const order = page.getByRole('combobox', { name: 'A 그룹 순서', exact: true })
  await expect.soft(order, '검색 중에는 전체 순서 변경을 막아야 한다').toBeDisabled()
  if (await order.isEnabled()) await order.selectOption('__ungrouped__')
  await page.getByRole('searchbox', { name: '항목 이름 검색', exact: true }).fill('')
  await expect.soft(page.locator('.my-map-editor-group-name'), '검색 중 조작은 숨겨진 전체 그룹 순서를 변경하지 않아야 한다').toHaveText(['그룹 없는 항목 0', 'A 3', 'B 0'])
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('groups-search-lock.png') })
})

test('my-map 작성 전범위: 면 첫 점 클릭으로 완료', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 기하 편집 계약')
  await startMap(page, '첫 점 완료 검증')
  await page.getByRole('button', { name: '면', exact: true }).click()
  await click(page, 780, 290); await click(page, 950, 290); await click(page, 950, 450)
  await click(page, 780, 290)
  await expect.poll(async () => (await features(page)).length).toBe(1)
})

test('my-map 작성 보완: 최근 점 스타일 상속·연속 추가·패널 닫기 이탈', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 작성 상태 계약')
  test.setTimeout(90000)
  await startMap(page, '연속 점과 이탈 검증')
  await page.getByRole('button', { name: '점', exact: true }).click()
  await click(page, 780, 300)
  await expect.poll(async () => (await saved(page, '연속 점과 이탈 검증'))?.items.length).toBe(1)
  await page.getByRole('spinbutton', { name: '크기', exact: true }).fill('13')
  await page.getByRole('spinbutton', { name: '크기', exact: true }).blur()
  const color = page.getByLabel('색', { exact: true })
  await color.evaluate((input) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, '#dc2626')
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await expect.poll(async () => (await saved(page, '연속 점과 이탈 검증'))?.items[0]?.style.color).toBe('#dc2626')
  await page.getByRole('button', { name: '← 항목 목록', exact: true }).click()
  await page.getByRole('button', { name: '점', exact: true }).click()
  await page.getByLabel('지점 연속 추가', { exact: true }).check()
  await click(page, 850, 340); await click(page, 920, 380)
  await expect.poll(async () => (await saved(page, '연속 점과 이탈 검증'))?.items.length).toBe(3)
  const points = (await saved(page, '연속 점과 이탈 검증')).items
  expect(points.slice(1).map((item) => item.style.color)).toEqual(['#dc2626', '#dc2626'])
  expect(points.slice(1).map((item) => item.style.pointSize)).toEqual([13, 13])
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('continuous-points-editor.png') })
  await page.getByRole('button', { name: '추가 마침', exact: true }).click()

  await page.getByRole('button', { name: '선', exact: true }).click()
  await click(page, 790, 440)
  await page.getByRole('button', { name: '내 지도 닫기', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '진행 중인 작업이 있습니다', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '계속 그리기', exact: true }).click()
  await expect(page.getByRole('button', { name: '도형 완료', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '내 지도 닫기', exact: true }).click()
  await page.getByRole('button', { name: '그냥 나가기', exact: true }).click()
  await expect(page.getByRole('region', { name: '내 지도 편집', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await saved(page, '연속 점과 이탈 검증'))?.items.length).toBe(3)
})

test('my-map 작성 보완: DMS 좌표 수정은 유효성 오류에서 기존 위치를 지킨다', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 좌표 입력 계약')
  test.setTimeout(90000)
  await startMap(page, '좌표 형식 검증')
  await page.getByRole('button', { name: '점', exact: true }).click()
  await click(page, 780, 300)
  await expect.poll(async () => (await saved(page, '좌표 형식 검증'))?.items.length).toBe(1)
  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  await page.getByRole('combobox', { name: '좌표 형식', exact: true }).selectOption('dms')
  await page.getByRole('textbox', { name: '위도', exact: true }).fill("N37°34'00\"")
  await page.getByRole('textbox', { name: '경도', exact: true }).fill("E126°58'41\"")
  await page.getByRole('button', { name: '완료', exact: true }).click()
  await expect.poll(async () => (await saved(page, '좌표 형식 검증'))?.items[0]?.geometry.coordinates).toEqual([126 + 58 / 60 + 41 / 3600, 37 + 34 / 60])

  await page.getByRole('button', { name: '지도에서 위치·형태 수정', exact: true }).click()
  await page.getByRole('textbox', { name: '위도', exact: true }).fill('37north')
  await expect(page.getByRole('alert')).toContainText('숫자')
  await page.getByRole('button', { name: '완료', exact: true }).click()
  await expect.poll(async () => (await saved(page, '좌표 형식 검증'))?.items[0]?.geometry.coordinates).toEqual([126 + 58 / 60 + 41 / 3600, 37 + 34 / 60])
})

test('my-map 작성 보완: 한글 조합 이름 수정은 한 번에 되돌리고 검색 이탈을 막는다', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 속성·이탈 계약')
  test.setTimeout(90000)
  await startMap(page, '속성 조합 검증')
  await page.getByRole('button', { name: '점', exact: true }).click()
  await click(page, 780, 300)
  await expect.poll(async () => (await saved(page, '속성 조합 검증'))?.items.length).toBe(1)

  const name = page.getByRole('textbox', { name: '이름', exact: true })
  await name.evaluate((input) => {
    input.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true, data: '' }))
    const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set
    setter.call(input, '한글 지점')
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true, data: '한글 지점' }))
  })
  await name.blur()
  await expect.poll(async () => (await saved(page, '속성 조합 검증'))?.items[0]?.name).toBe('한글 지점')
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.poll(async () => (await saved(page, '속성 조합 검증'))?.items[0]?.name).toBe('지점 1')
  await page.getByRole('button', { name: '다시하기', exact: true }).click()
  await expect.poll(async () => (await saved(page, '속성 조합 검증'))?.items[0]?.name).toBe('한글 지점')

  await page.getByRole('button', { name: '선', exact: true }).click()
  await click(page, 810, 350)
  await page.getByRole('button', { name: '검색', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '진행 중인 작업이 있습니다', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '계속 그리기', exact: true }).click()
  await expect(page.getByRole('button', { name: '도형 완료', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '검색', exact: true }).click()
  await page.getByRole('button', { name: '그냥 나가기', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '검색', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: '내 지도 편집', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await saved(page, '속성 조합 검증'))?.items).toHaveLength(1)
})

test('my-map 그룹 보완: 새 그룹 묶기·순서 메뉴·해제·다중 드래그 한 번 되돌리기', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 그룹 편집 계약')
  test.setTimeout(120000)
  await startMap(page, '그룹 보완 검증')
  await page.getByRole('textbox', { name: '새 그룹 이름', exact: true }).fill('A')
  await page.getByRole('button', { name: '그룹 추가', exact: true }).click()
  await page.getByRole('button', { name: '좌표 여러 줄 입력', exact: true }).click()
  const bulk = page.getByRole('region', { name: '좌표 여러 줄 입력', exact: true })
  await bulk.getByRole('combobox', { name: '대상 그룹' }).selectOption({ label: 'A' })
  await bulk.locator('textarea').fill('첫째\t37\t127\n둘째\t37.1\t127.1\n셋째\t37.2\t127.2')
  await bulk.getByRole('button', { name: '점 3개 추가', exact: true }).click()
  await page.getByRole('button', { name: '선택', exact: true }).click()
  await page.getByRole('checkbox', { name: '첫째 선택', exact: true }).check()
  await page.getByRole('checkbox', { name: '셋째 선택', exact: true }).check()
  await page.getByRole('combobox', { name: '선택 항목 이동할 그룹', exact: true }).selectOption('__new__')
  await page.getByRole('textbox', { name: '선택 항목의 새 그룹 이름', exact: true }).fill('묶음')
  await page.getByRole('button', { name: '그룹으로 묶기', exact: true }).click()
  const group = (name) => page.locator('.my-map-editor-group').filter({ has: page.getByRole('button', { name: new RegExp(`^${name} \\d+$`) }) })
  await expect(group('묶음').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(group('묶음')).toHaveCount(0)
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●둘째', '●셋째'])
  await page.getByRole('button', { name: '다시하기', exact: true }).click()
  await page.getByRole('button', { name: '선택 마침', exact: true }).click()
  await page.getByRole('combobox', { name: '첫째 항목 순서', exact: true }).selectOption('down')
  await expect(group('묶음').locator('.my-map-editor-item-name')).toHaveText(['●셋째', '●첫째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(group('묶음').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째'])
  const virtualOrder = page.getByRole('combobox', { name: '그룹 없는 항목 그룹 순서', exact: true })
  await virtualOrder.selectOption('__last__')
  await expect(page.locator('.my-map-editor-group-name')).toHaveText(['A 1', '묶음 2', '그룹 없는 항목 0'])
  await virtualOrder.selectOption('__last__')
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(page.locator('.my-map-editor-group-name')).toHaveText(['그룹 없는 항목 0', 'A 1', '묶음 2'])
  await page.getByRole('button', { name: '묶음 그룹 삭제', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2개 항목')
  await page.getByRole('button', { name: '취소', exact: true }).click()
  await page.getByRole('button', { name: '묶음 그룹 해제', exact: true }).click()
  await expect(group('묶음')).toHaveCount(0)
  await expect(group('그룹 없는 항목').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await page.getByRole('button', { name: '선택', exact: true }).click()
  await page.getByRole('checkbox', { name: '첫째 선택', exact: true }).check()
  await page.getByRole('checkbox', { name: '셋째 선택', exact: true }).check()
  await group('묶음').locator('.my-map-editor-item').first().dragTo(group('A').locator('.my-map-editor-item').first())
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째', '●둘째'])
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(group('A').locator('.my-map-editor-item-name')).toHaveText(['●둘째'])
  await expect(group('묶음').locator('.my-map-editor-item-name')).toHaveText(['●첫째', '●셋째'])
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('group-actions.png') })
})

test('my-map 그룹 보완: 긴 목록 드래그 자동 스크롤·접힌 그룹 펼침·외부 드롭 무변경', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 그룹 드래그 계약')
  test.setTimeout(90000)
  await startMap(page, '긴 그룹 검증')
  for (const name of ['A', 'B']) {
    await page.getByRole('textbox', { name: '새 그룹 이름', exact: true }).fill(name)
    await page.getByRole('button', { name: '그룹 추가', exact: true }).click()
  }
  await page.getByRole('button', { name: '좌표 여러 줄 입력', exact: true }).click()
  const bulk = page.getByRole('region', { name: '좌표 여러 줄 입력', exact: true })
  await bulk.getByRole('combobox', { name: '대상 그룹' }).selectOption({ label: 'A' })
  await bulk.locator('textarea').fill(Array.from({ length: 30 }, (_, i) => `지점${i}\t37.${i}\t127`).join('\n'))
  await bulk.getByRole('button', { name: '점 30개 추가', exact: true }).click()
  const item = page.locator('.my-map-editor-item').first()
  // 고정 패널 헤더 뒤에서 시작하면 native dragstart가 안 날 수 있다. 실제 항목을
  // 스크롤 영역 중앙에 놓고 시작을 관찰해야 자동 스크롤 자체를 검증할 수 있다.
  await item.evaluate((element) => element.scrollIntoView({ block: 'center' }))
  const grip = await item.locator('.my-map-editor-grip').boundingBox()
  const panel = page.locator('.my-map-panel-content')
  const bounds = await panel.boundingBox(), before = await panel.evaluate((element) => element.scrollTop)
  await page.evaluate(() => { window.__myMapFirstDragStarts = 0; window.addEventListener('dragstart', () => { window.__myMapFirstDragStarts += 1 }, { once: true }) })
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2)
  await page.mouse.down()
  await page.mouse.move(grip.x + grip.width / 2 + 15, grip.y + grip.height / 2 + 10, { steps: 5 })
  await expect.poll(() => page.evaluate(() => window.__myMapFirstDragStarts)).toBe(1)
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height - 10, { steps: 12 })
  await expect.poll(() => panel.evaluate((element) => element.scrollTop)).toBeGreaterThan(before + 150)
  await page.mouse.move(800, 350, { steps: 5 }); await page.mouse.up()
  const stoppedAt = await panel.evaluate((element) => element.scrollTop)
  await page.evaluate(() => new Promise((resolve) => { let frames = 0; const tick = () => ++frames === 15 ? resolve() : requestAnimationFrame(tick); requestAnimationFrame(tick) }))
  expect(await panel.evaluate((element) => element.scrollTop)).toBe(stoppedAt)
  expect((await saved(page, '긴 그룹 검증')).items).toHaveLength(30)
  // Keep the source away from the fixed panel header before starting the second drag.
  await page.getByRole('button', { name: 'B 접기', exact: true }).click()
  await item.evaluate((element) => element.scrollIntoView({ block: 'center' }))
  await page.evaluate(() => { window.__myMapDragStarts = 0; window.addEventListener('dragstart', () => { window.__myMapDragStarts += 1 }) })
  const source = await item.locator('.my-map-editor-grip').boundingBox()
  await page.mouse.move(source.x + 8, source.y + 8); await page.mouse.down()
  await page.mouse.move(source.x + 23, source.y + 18, { steps: 5 })
  await expect.poll(() => page.evaluate(() => window.__myMapDragStarts)).toBe(1)
  const destination = page.getByRole('button', { name: 'B 0', exact: true })
  await destination.scrollIntoViewIfNeeded()
  const target = await destination.boundingBox()
  await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 10 })
  await page.mouse.move(target.x + target.width / 2 + 1, target.y + target.height / 2)
  await expect(page.getByRole('button', { name: 'B 접기', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.mouse.up()
  await expect(page.getByRole('button', { name: 'B 1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect(page.getByRole('button', { name: 'B 0', exact: true })).toBeVisible()
})
