import { fileURLToPath } from 'node:url'
import { test, expect } from '../fixtures.mjs'
import { CURRENT_VERSION } from '../../src/features/about/changelog.js'

const KMZ = fileURLToPath(new URL('../../test/fixtures/my-map/folders.kmz', import.meta.url))
const META = '<?xml version="1.0"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>메타자료</name><Placemark><name>참고점</name><description><![CDATA[<p>원본 설명</p>]]></description><ExtendedData><Data name="미지 필드"><value>0</value></Data><Data name="미지 필드"><value>false</value></Data></ExtendedData><Point><coordinates>127,37,100</coordinates></Point></Placemark></Document></kml>'

async function open(page) {
  await page.addInitScript((version) => { localStorage.setItem('amo.tour.v1.done', 'true'); localStorage.setItem('projectamo:lastSeenVersion', version) }, CURRENT_VERSION)
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: '내 지도', exact: true }).click()
}
async function records(page) {
  return page.evaluate(async () => {
    const db = await new Promise((resolve) => { const r = indexedDB.open('projectamo-my-map-account-v1'); r.onsuccess = () => resolve(r.result) })
    const rows = await new Promise((resolve) => { const r = db.transaction('completed').objectStore('completed').getAll(); r.onsuccess = () => resolve(r.result) })
    db.close(); return rows.map((row) => row.document.document ?? row.document)
  })
}
const saved = async (page, name) => (await records(page)).find((document) => document.name === name)
async function chooseFile(page, button, file) {
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: button, exact: true }).click()
  await (await chooser).setFiles(file)
}
const convertDialog = (page) => page.getByRole('dialog', { name: '편집본으로 가져오기', exact: true })

test('my-map 파일 보완: 현재 지도 KMZ 추가·취소·undo·파일 드롭·원본 메타데이터', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 편집 파일 흐름')
  test.setTimeout(120000)
  await open(page)
  await page.getByRole('button', { name: '새 지도', exact: true }).click()
  await page.getByRole('textbox', { name: '지도 이름', exact: true }).fill('병합 지도')
  await page.getByRole('button', { name: '만들기', exact: true }).click()
  await page.waitForFunction(() => window.__map?.getLayer('my-map-edit-line'))
  await page.evaluate(() => window.__map.jumpTo({ center: [127, 37], zoom: 8 }))
  await page.getByRole('button', { name: '점', exact: true }).click()
  await page.locator('.mapboxgl-canvas').click({ position: { x: 800, y: 320 } })
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.length).toBe(1)
  const original = await saved(page, '병합 지도')

  await chooseFile(page, 'KML/KMZ 추가', KMZ)
  await expect(convertDialog(page).locator('.my-map-preview-counts strong')).toHaveText(['3', '3', '0', '0'])
  await expect(convertDialog(page)).toContainText('병합 지도')
  await convertDialog(page).getByRole('button', { name: '취소', exact: true }).click()
  expect((await saved(page, '병합 지도')).items).toEqual(original.items)

  await chooseFile(page, 'KML/KMZ 추가', KMZ)
  await expect(convertDialog(page).getByRole('button', { name: '현재 지도에 추가', exact: true })).toBeEnabled()
  await convertDialog(page).getByRole('button', { name: '현재 지도에 추가', exact: true }).click()
  await expect(convertDialog(page)).toHaveCount(0)
  await expect(page.locator('.my-map-selection-actions')).toContainText('3개 선택')
  await expect(page.locator('.my-map-editor-item input[type=checkbox]:checked')).toHaveCount(3)
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.length).toBe(4)
  const appended = await saved(page, '병합 지도')
  expect(appended.id).toBe(original.id)
  expect(appended.items[0]).toEqual(original.items[0])
  expect(appended.groups).toHaveLength(3)
  expect(appended.groups.every((group) => group.parentId === null)).toBe(true)
  expect(appended.groups.map((group) => group.name)).toContain('RKTA TAEAN / 출항절차')
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.length).toBe(1)
  expect((await saved(page, '병합 지도')).groups).toHaveLength(0)
  await page.getByRole('button', { name: '다시하기', exact: true }).click()
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.length).toBe(4)
  expect((await saved(page, '병합 지도')).items.map((item) => item.id)).toEqual(appended.items.map((item) => item.id))

  const data = await page.evaluateHandle((text) => { const transfer = new DataTransfer(); transfer.items.add(new File([text], 'metadata.kml', { type: 'application/vnd.google-earth.kml+xml' })); return transfer }, META)
  await page.locator('.my-map-editor-item').first().dispatchEvent('drop', { dataTransfer: data })
  await expect(convertDialog(page).getByRole('button', { name: '현재 지도에 추가', exact: true })).toBeEnabled()
  await convertDialog(page).getByRole('button', { name: '현재 지도에 추가', exact: true }).click()
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.length).toBe(5)
  const imported = (await saved(page, '병합 지도')).items.find((item) => item.name === '참고점')
  expect(imported.source.metadataEntries.filter((entry) => entry.key === '미지 필드').map((entry) => entry.value)).toEqual(['0', 'false'])
  expect(imported.geometry.coordinates).toEqual([127, 37, 100])
  await page.getByRole('button', { name: '선택 마침', exact: true }).click()
  await page.getByRole('button', { name: '참고점', exact: true }).click()
  await page.getByRole('textbox', { name: '메모', exact: true }).fill('사용자가 수정한 메모')
  await page.getByRole('button', { name: '편집 마침', exact: true }).click()
  await expect(page.getByRole('region', { name: '사용자 메모', exact: true })).toContainText('사용자가 수정한 메모')
  await expect(page.locator('.my-map-detail')).toContainText('원본 설명')
  await expect.poll(async () => (await saved(page, '병합 지도'))?.items.find((item) => item.name === '참고점')?.description).toBe('사용자가 수정한 메모')
  const final = await saved(page, '병합 지도')
  expect(final.items.find((item) => item.name === '참고점').source).toEqual(imported.source)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: '내 지도', exact: true }).click()
  await expect(page.locator('.my-map-panel h1')).toHaveText('병합 지도')
  expect((await saved(page, '병합 지도')).items).toEqual(final.items)
  await page.getByRole('button', { name: '목록', exact: true }).click()
  const imports = page.getByTestId('my-map-files').locator('.my-map-library-section').filter({ has: page.locator('.my-map-section-heading', { hasText: '가져온 지도' }) })
  await expect(imports.locator('.my-map-document-row')).toHaveCount(3)
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('append-originals-preserved.png') })
})

test('my-map 파일 보완: 목록에서 새 편집본·개인 지도 복제·재열기·독립 삭제', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', '데스크톱 개인 지도 관리')
  test.setTimeout(120000)
  await open(page)
  await chooseFile(page, '편집본으로 가져오기', KMZ)
  await convertDialog(page).getByRole('textbox', { name: '편집본 이름', exact: true }).fill('원본 편집 지도')
  await expect(convertDialog(page).getByRole('button', { name: '편집본 만들기', exact: true })).toBeEnabled()
  await convertDialog(page).getByRole('button', { name: '편집본 만들기', exact: true }).click()
  await expect(page.locator('.my-map-panel h1')).toHaveText('원본 편집 지도')
  const original = await saved(page, '원본 편집 지도')
  expect(original.items).toHaveLength(3)
  await page.getByRole('button', { name: '전체 숨기기', exact: true }).click()
  await page.getByTestId('my-map-file-menu').click()
  await page.getByRole('menuitem', { name: '지도 복제', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '지도 복제', exact: true })
  await expect(dialog).toContainText('숨긴 항목을 포함해 3개 항목')
  await dialog.getByRole('textbox', { name: '사본 이름', exact: true }).fill('개인 사본')
  await dialog.getByRole('button', { name: '복제하기', exact: true }).click()
  await expect(page.locator('.my-map-panel h1')).toHaveText('개인 사본')
  const copy = await saved(page, '개인 사본')
  expect(copy.id).not.toBe(original.id)
  const originalIds = new Set([...original.items, ...original.groups].map((entry) => entry.id))
  expect([...copy.items, ...copy.groups].every((entry) => !originalIds.has(entry.id))).toBe(true)
  expect(copy.items.map(({ id, groupId, ...item }) => item)).toEqual(original.items.map(({ id, groupId, ...item }) => item))
  expect(copy.source).toEqual(original.source)
  await page.getByRole('button', { name: '추가하기', exact: true }).click()
  await page.getByRole('textbox', { name: '지도 이름', exact: true }).fill('수정한 개인 사본')
  await page.getByRole('button', { name: '편집 마침', exact: true }).click()
  await expect.poll(async () => (await saved(page, '수정한 개인 사본'))?.id).toBe(copy.id)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: '내 지도', exact: true }).click()
  await expect(page.locator('.my-map-panel h1')).toHaveText('수정한 개인 사본')
  await page.getByRole('button', { name: '목록', exact: true }).click()
  await page.getByRole('button', { name: '수정한 개인 사본 삭제', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('3개 항목')
  await page.getByRole('dialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect.poll(async () => (await records(page)).some((document) => document.id === copy.id)).toBe(false)
  expect((await saved(page, '원본 편집 지도')).items).toEqual(original.items)
  await expect(page.getByTestId('my-map-files')).toContainText('folders.kmz')
  await page.getByRole('button', { name: '원본 편집 지도 삭제', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect.poll(async () => (await records(page)).length).toBe(0)
  await expect(page.getByTestId('my-map-files')).toContainText('folders.kmz')
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('copies-deleted-original-kept.png') })
})
