import { test, expect } from '@playwright/test'
import { installPresentationFixture } from '../organization-presentation-fixture.mjs'

test('organization-presentation-pin: candidate, altitude, layout, expansion and style keep exact resources until apply', async ({ page }) => {
  test.setTimeout(90000)
  const pageErrors = []
  page.on('pageerror', error => pageErrors.push(error.message))
  const state = await installPresentationFixture(page)
  await page.goto('/lounge/11/briefings/81/present')
  await expect(page.locator('.op-footer')).toContainText('pinned-1', { timeout: 30000 })
  await expect.poll(() => page.evaluate(() => Boolean(document.querySelector('.op-grid .mapboxgl-map')?.__projectamoMap))).toBe(true)
  await page.evaluate(() => { window.__map = document.querySelector('.op-grid .mapboxgl-map').__projectamoMap })
  await expect.poll(() => page.evaluate(() => window.__map?.getSource('organization-pinned-satellite')?.serialize()?.url || '')).toContain('/fixture/1.png')
  await expect.poll(() => state.models.filter(url => url.includes('/field?')).length).toBeGreaterThan(0)
  const altitude = page.locator('.pressure-level-slider [role=slider]').first()
  await expect(altitude).toBeVisible()
  state.holdModel = true
  await altitude.focus()
  await page.keyboard.press('ArrowUp')
  await expect.poll(() => state.models.some(url => url.includes('level=700hPa') && url.includes('revision=kim-1-700hPa'))).toBe(true)
  await expect.poll(() => Boolean(state.releaseModel)).toBe(true)
  await page.evaluate(() => { window.__presentationBaseMap = window.__map })
  state.generation = 2
  await page.getByRole('button', { name: '새 자료 확인', exact: true }).click()
  await expect(page.getByRole('button', { name: /준비된 새 자료 적용/ })).toBeEnabled()
  await expect(page.locator('.op-footer')).toContainText('pinned-1')
  await page.getByRole('button', { name: 'A 기존 배치', exact: true }).click()
  await expect(page.locator('.op-footer')).toContainText('pinned-1')
  await page.getByRole('button', { name: '평면 기상 지도 확대', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '발표 자료 확대' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.__map?.getSource('organization-pinned-satellite')?.serialize()?.url || '')).toContain('/fixture/1.png')
  await page.keyboard.press('Escape')
  await page.evaluate(() => { window.__map = document.querySelector('.op-grid .mapboxgl-map').__projectamoMap })
  await page.getByRole('button', { name: 'B 지도 중심', exact: true }).click()
  await page.evaluate(() => { window.__map = document.querySelector('.op-grid .mapboxgl-map').__projectamoMap })
  await page.evaluate(() => window.__map.setStyle({ version: 8, glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf', sources: {}, layers: [{ id: 'fixture-background', type: 'background', paint: { 'background-color': '#eaf0f4' } }] }))
  await expect.poll(() => page.evaluate(() => window.__map?.getSource('organization-pinned-satellite')?.serialize()?.url || '')).toContain('/fixture/1.png')
  expect(state.models.filter(url => url.includes('/field?')).every(url => url.includes('tmfc=2026090906') && url.includes('revision=kim-1-'))).toBe(true)
  await page.getByRole('button', { name: /준비된 새 자료 적용/ }).click()
  await expect(page.locator('.op-footer')).toContainText('pinned-2')
  await expect.poll(() => page.evaluate(() => window.__map?.getSource('organization-pinned-satellite')?.serialize()?.url || '')).toContain('/fixture/2.png')
  await expect.poll(() => state.models.some(url => url.includes('revision=kim-2-'))).toBe(true)
  const deliveries = await page.evaluate(() => window.__deliveredPresentationModels.length)
  state.releaseModel()
  await expect.poll(() => page.evaluate(() => window.__deliveredPresentationModels.length)).toBeGreaterThan(deliveries)
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await expect(page.locator('.op-grid .map-view-wrapper')).toHaveAttribute('data-wind-run', '2026091006')
  state.expireFrame = true
  await page.evaluate(() => window.__map.setStyle({ version: 8, glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf', sources: {}, layers: [{ id: 'expired-background', type: 'background', paint: { 'background-color': '#eaf0f4' } }] }))
  await expect(page.locator('.organization-map__status')).toContainText(/위성.*실패/, { timeout: 15000 })
  const frameRequests = state.frameRequests
  await page.waitForTimeout(500)
  expect(state.frameRequests).toBe(frameRequests)
  expect(state.applies).toEqual(['pinned-1', 'pinned-2'])
  expect(pageErrors).toEqual([])
  await page.screenshot({ path: `../artifacts/organization-lounge/${test.info().project.name}-pinned-final.png` })
})
